### ISSUE TITLE
plágio

### ISSUE THREAD

**Issue by folivetti** [ufabc-students-bcc/awesome-disciplinas#32]
https://github.com/ufabc-students-bcc/awesome-disciplinas/blob/897e7d0ebfea8a0c382c690e99d87bc5f8a408ea/obrigatorias/inteligencia-artificial/Olivetti/Projetos/Arthur_H_Fernandes_CartPole/arthur_cartpole.py#L1

cópia de https://github.com/philtabor/OpenAI-Cartpole/blob/master/cartpole_qlearning.py (acho melhor remover do repositório uma vez que não faz referência ao original)

**Comment by has256** [comment]
@arthurhf consegue checar?! 

Achei melhor deixar ainda mais explícito, uma vez que o sistema de notificações do github tende à ser pouco efetivo. :smiley:

**Comment by arthurhf** [comment]
Sim, eu peguei dessa fonte mesmo. Não consegui criar um do zero pois não tenho conhecimento em python. Pode remover do repositório como o Professor disse.
