### ISSUE TITLE
Não está levando em conta o custo do caminho

### ISSUE THREAD

**Issue by folivetti** [ufabc-students-bcc/awesome-disciplinas#34]
https://github.com/ufabc-students-bcc/awesome-disciplinas/blob/897e7d0ebfea8a0c382c690e99d87bc5f8a408ea/obrigatorias/inteligencia-artificial/Olivetti/Projetos/restaUm/restaUm.py#L11

lembre-se que a escolha do próximo nó no A* é f = g + h

**Comment by has256** [comment]
@FilipiBrabo consegue checar?! 

Achei melhor deixar ainda mais explícito, uma vez que o sistema de notificações do github tende à ser pouco efetivo. :smiley:

**Comment by folivetti** [comment]
Perdão, me esqueci que todos os mantenedores recebem a notificação :)

**Comment by has256** [comment]
Sem problemas, hahahahah, vou ver se consigo alertar os envolvidos! Fique à vontade pra mapear feedbacks via issues, ferramenta serve exatamente pra isso!

**Comment by FilipiBrabo** [comment]
Oi professor, não entendi a pergunta. Você fala no A-estrela?

**Comment by folivetti** [comment]
Isso, no A-estrela você escolhe o próximo nó a expandir utilizando apenas h, mas tem que somar g tb!

**Comment by FilipiBrabo** [comment]
Ah, é verdade. Acabou sendo gulosa ao invés de ser A-estrela. Eu lembro que
não consegui pensar em um g adequado pro problema, tentei fazer g crescer
linear com a altura, mas isso implicaria na exploração dos nós com menor
altura primeiro.
Acabei deixando só o h  e esqueci de mudar o nome da busca, me desculpe.
